import esbuild from "esbuild";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import process from "process";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";
const embeddedAssets = {
  name: "embedded-assets",
  setup(build) {
    build.onResolve({ filter: /^embedded-asset:/ }, (args) => ({
      path: args.path.slice("embedded-asset:".length),
      namespace: "embedded-asset",
    }));
    build.onLoad({ filter: /.*/, namespace: "embedded-asset" }, (args) => {
      const file = resolve(args.path);
      const isBinary = /\.(onnx|wasm|bin)$/i.test(file);
      const content = isBinary
        ? readFileSync(file).toString("base64")
        : readFileSync(file, "utf8");
      return { contents: `export default ${JSON.stringify(content)};`, loader: "js" };
    });
  },
};

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ["main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  plugins: [embeddedAssets],
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
